### ISSUE TITLE
本库怎么用docker部署

### ISSUE THREAD

**Issue by ljhnchina** [icepage/SmsCodeWebhook#1]
本库怎么用docker部署
使用
docker pull icepage/SmsCodeWebhook:latest    
无法部署

**Comment by ljhnchina** [comment]
> 本库怎么用docker部署 使用 docker pull icepage/SmsCodeWebhook:latest 无法步数

**Comment by icepage** [comment]
@ljhnchina 已支持docker 部署，看最新文档
